package com.example.data.sample

import com.example.data.model.AcademicClass
import com.example.data.model.BadgeItem
import com.example.data.model.CalendarEvent
import com.example.data.model.CalendarEventType
import com.example.data.model.EncryptedNote
import com.example.data.model.ForumAnswer
import com.example.data.model.ForumPost
import com.example.data.model.MDCATSubject
import com.example.data.model.QuizQuestion
import com.example.data.model.StudyGroup
import com.example.data.model.StudyMaterial
import com.example.data.model.StudyNoteDraft
import com.example.data.model.VideoLecture

object MDCATSyllabusData {

  val studyMaterials: List<StudyMaterial> = listOf(
    StudyMaterial(
      id = "bio_1",
      subject = MDCATSubject.BIOLOGY,
      title = "Bioenergetics: Glycolysis & Krebs Cycle",
      chapter = "Cellular Metabolism",
      readTimeMin = 14,
      highYieldPriority = "ESSENTIAL",
      keyConcepts = listOf(
        "Glycolysis occurs in cytoplasm, yields net 2 ATP, 2 NADH, 2 Pyruvate per glucose.",
        "Hexokinase & Phosphofructokinase-1 (PFK-1) are key irreversible rate-limiting enzymes.",
        "Link reaction: Pyruvate dehydrogenase converts pyruvate to Acetyl-CoA with loss of CO2.",
        "Krebs Cycle occurs in mitochondrial matrix, producing 3 NADH, 1 FADH2, 1 GTP per turn.",
        "Oxidative Phosphorylation uses complexes I-IV on inner mitochondrial membrane; Complex II (Succinate Dehydrogenase) does not pump protons."
      ),
      mnemonics = listOf(
        "Krebs Cycle Substrates: 'Can I Keep Selling Sex For Money, Officer?' (Citrate, Isocitrate, α-Ketoglutarate, Succinyl-CoA, Succinate, Fumarate, Malate, Oxaloacetate)",
        "PFK-1 Regulation: 'ATP & Citrate stop the gate; AMP & F-2,6-BP accelerate.'"
      ),
      formulas = listOf(
        "Net Aerobic Glucose Yield: 30-32 ATP",
        "1 NADH ≈ 2.5 ATP (via Complex I)",
        "1 FADH2 ≈ 1.5 ATP (via Complex II)"
      ),
      contentMarkdown = """
# Bioenergetics & Cellular Respiration

Cellular respiration is one of the most frequently tested topics on the MDCAT. Master the compartmentalization, regulatory enzymes, and net electron yields.

## 1. Glycolysis (Cytosol)
- **Anaerobic pathway** present in all living cells.
- **Preparatory Phase**: 2 ATP invested (Hexokinase & PFK-1).
- **Payoff Phase**: 4 ATP generated by substrate-level phosphorylation; 2 NADH produced by GAPDH.
- **Net Gain**: 2 ATP + 2 NADH + 2 Pyruvate.

## 2. Link Reaction (Mitochondrial Matrix)
- Pyruvate (3C) + CoA-SH + NAD+ → Acetyl-CoA (2C) + CO2 + NADH + H+.
- Catalyzed by multi-enzyme complex **Pyruvate Dehydrogenase (PDH)**.

## 3. Krebs Cycle (Tricarboxylic Acid Cycle)
- Oxaloacetate (4C) condenses with Acetyl-CoA (2C) to form Citrate (6C) via Citrate Synthase.
- Rate limiting step: **Isocitrate Dehydrogenase** (stimulated by ADP, inhibited by ATP & NADH).
- Substrate-level phosphorylation step: Succinyl-CoA Synthetase yields 1 GTP.

## 4. Electron Transport Chain & Chemiosmosis
- Complex I (NADH dehydrogenase): pumps 4 H+.
- Complex II (Succinate dehydrogenase): transfers electrons from FADH2 to CoQ; does **NOT** pump protons!
- Complex III (Cytochrome bc1): pumps 4 H+.
- Complex IV (Cytochrome c oxidase): pumps 2 H+, reduces O2 to H2O.
- ATP Synthase (Complex V): utilizes proton motive force to synthesize ATP.
      """.trimIndent()
    ),

    StudyMaterial(
      id = "bio_2",
      subject = MDCATSubject.BIOLOGY,
      title = "Enzymes & Michaelis-Menten Kinetics",
      chapter = "Biological Molecules",
      readTimeMin = 10,
      highYieldPriority = "HIGH",
      keyConcepts = listOf(
        "Enzymes lower activation energy (Ea) without altering equilibrium constant (Keq) or ΔG.",
        "Competitive Inhibition: Km increases (lower affinity), Vmax remains unchanged. Overcome by adding excess substrate.",
        "Non-competitive Inhibition: Km remains unchanged, Vmax decreases. Inhibitor binds allosteric site regardless of substrate binding.",
        "Uncompetitive Inhibition: Both Km and Vmax decrease proportionally.",
        "Optimum temperature and pH alter enzyme tertiary conformation by disrupting hydrogen and ionic bonds."
      ),
      mnemonics = listOf(
        "Competitive Inhibition: 'Competitors fight for the same spot; Km climbs higher, but top speed (Vmax) is still reachable.'",
        "Non-competitive: 'No competition for the active site; Vmax drops down, Km sticks around.'"
      ),
      formulas = listOf(
        "Lineweaver-Burk Plot: 1/V = (Km/Vmax)(1/[S]) + 1/Vmax",
        "Y-intercept = 1/Vmax",
        "X-intercept = -1/Km"
      ),
      contentMarkdown = """
# Enzyme Kinetics & Catalytic Action

MDCAT questions heavily target the behavior of inhibitors on Lineweaver-Burk double reciprocal plots and Michaelis-Menten hyperbolic curves.

## Kinetic Parameters
- **Km (Michaelis Constant)**: Substrate concentration at 1/2 Vmax. Inversely related to enzyme-substrate affinity. A lower Km indicates higher affinity.
- **Vmax**: Maximum velocity achieved when all enzyme active sites are saturated.

## Inhibition Types Matrix
1. **Competitive Inhibitor**:
   - Structurally mimics substrate.
   - Competes directly for the active site.
   - **Km increases**, **Vmax unchanged**.
2. **Non-competitive Inhibitor**:
   - Binds allosterically to both free enzyme (E) and enzyme-substrate complex (ES).
   - **Km unchanged**, **Vmax decreases**.
      """.trimIndent()
    ),

    StudyMaterial(
      id = "chem_1",
      subject = MDCATSubject.CHEMISTRY,
      title = "Chemical Equilibrium & Le Chatelier's Principle",
      chapter = "Physical Chemistry",
      readTimeMin = 12,
      highYieldPriority = "HIGH",
      keyConcepts = listOf(
        "Equilibrium constant Kc depends SOLELY on temperature; catalysts, pressure, and concentration do NOT change Kc.",
        "Exothermic reaction (ΔH < 0): Increasing temperature shifts equilibrium backward, decreasing Kc.",
        "Endothermic reaction (ΔH > 0): Increasing temperature shifts equilibrium forward, increasing Kc.",
        "Pressure increase shifts gaseous equilibrium toward fewer moles of gas.",
        "Catalyst accelerates both forward and backward rates equally; equilibrium is reached faster but position is unchanged."
      ),
      mnemonics = listOf(
        "Equilibrium Shift: 'Add shifts Away, Remove shifts Toward.'",
        "Pressure: 'More squeeze (pressure) pushes toward fewer heads (moles).'"
      ),
      formulas = listOf(
        "Kp = Kc * (RT)^(Δn)",
        "Δn = moles of gaseous products - moles of gaseous reactants",
        "pH + pOH = 14 (at 25°C)",
        "Kw = [H+][OH-] = 1.0 x 10^-14"
      ),
      contentMarkdown = """
# Chemical Equilibrium & Industrial Processes

Master the dynamic nature of chemical equilibrium and quantitative shifts under Le Chatelier's Principle.

## Le Chatelier's Principle
If a chemical system at dynamic equilibrium experiences a change in concentration, temperature, or pressure, the system shifts to counteract the imposed disturbance.

### Haber Process: N2(g) + 3H2(g) ⇌ 2NH3(g) (ΔH = -92 kJ/mol)
- Exothermic forward reaction.
- High pressure (200 atm) shifts equilibrium right (4 moles → 2 moles).
- Optimum temperature (450°C) is a compromise between yield and reaction rate.
- Finely divided Iron (Fe) acts as catalyst with promoter Al2O3.
      """.trimIndent()
    ),

    StudyMaterial(
      id = "chem_2",
      subject = MDCATSubject.CHEMISTRY,
      title = "Organic Carbonyls: Aldehydes & Ketones",
      chapter = "Organic Chemistry",
      readTimeMin = 15,
      highYieldPriority = "ESSENTIAL",
      keyConcepts = listOf(
        "Carbonyl carbon is sp2 hybridized, planar, electrophilic due to polarized C=O bond.",
        "Aldehydes are more reactive than ketones due to less steric hindrance and smaller electron-donating inductive effect.",
        "Tollens' Reagent [Ag(NH3)2]+ oxidizes aldehydes giving silver mirror; ketones do not react.",
        "Fehling's solution yields red precipitate of Cu2O with aliphatic aldehydes.",
        "Iodoform Test (I2/NaOH) gives yellow crystal CHI3 with methyl ketones and ethanol/secondary methyl alcohols."
      ),
      mnemonics = listOf(
        "Iodoform Positive: 'CH3-C=O or CH3-CH(OH)- give yellow crystals to remember.'",
        "Tollens vs Fehling: 'Tollens tests all aldehydes; Fehling fears benzaldehyde (only aliphatic).'"
      ),
      formulas = listOf(
        "Oxidation: 1° Alcohol → Aldehyde → Carboxylic Acid",
        "Oxidation: 2° Alcohol → Ketone (resistant to further mild oxidation)"
      ),
      contentMarkdown = """
# Aldehydes, Ketones & Nucleophilic Additions

Nucleophilic addition is the signature reaction of carbonyl compounds.

## Key Distinguishing Tests
1. **Tollens' Test (Silver Mirror)**:
   - Reagent: Ammoniacal silver nitrate.
   - Observation: Brilliant silver mirror coats inner glass wall.
   - Result: Positive for all aldehydes (aliphatic & aromatic).
2. **Fehling's & Benedict's Tests**:
   - Observation: Brick-red precipitate of Cuprous Oxide (Cu2O).
   - Result: Positive for aliphatic aldehydes, negative for benzaldehyde & ketones.
3. **2,4-DNPH (Brady's Reagent)**:
   - Condensation test for ALL aldehydes and ketones; produces orange-red hydrazone crystals.
      """.trimIndent()
    ),

    StudyMaterial(
      id = "phys_1",
      subject = MDCATSubject.PHYSICS,
      title = "Work, Energy & Gravitational Potential",
      chapter = "Mechanics",
      readTimeMin = 12,
      highYieldPriority = "HIGH",
      keyConcepts = listOf(
        "Work = F · d · cos(θ). Work is zero if displacement is perpendicular to force (e.g. centripetal force).",
        "Work-Energy Theorem: Total net work done on a body equals change in its kinetic energy (W = ΔK).",
        "Absolute Gravitational Potential Energy: U = -G(Mm)/r. Note the negative sign; zero potential is at infinity.",
        "Escape Velocity: vesc = √(2gR) = √(2GM/R) ≈ 11.2 km/s on Earth's surface.",
        "Power = Work / time = F · v. Maximum power efficiency happens under impedance matching."
      ),
      mnemonics = listOf(
        "Zero Work Scenarios: 'Carrying a bucket walking flat, circular orbit where gravity is flat.' (θ = 90°, cos90 = 0)"
      ),
      formulas = listOf(
        "Kinetic Energy: K = (1/2)mv² = p²/(2m)",
        "Escape Velocity: vesc = √(2gR)",
        "Orbital Velocity: vorb = √(gR) = vesc / √2",
        "Instantaneous Power: P = F · v"
      ),
      contentMarkdown = """
# Work, Power & Conservation of Energy

A cornerstone topic on MDCAT Physics. Pay close attention to dot products and conservative vs non-conservative fields.

## Conservative Fields
- Work done around any closed loop is zero (∮ F·dr = 0).
- Work done is independent of the path taken.
- Gravitational, electrostatic, and elastic spring forces are conservative.
- Frictional and viscous forces are non-conservative.

## Escape Velocity Derivation
Equating total mechanical energy at Earth's surface to zero at infinity:
(1/2)m(vesc)² - G(Mm)/R = 0
vesc = √(2GM/R) = √(2gR)
For Earth (g ≈ 9.8 m/s², R ≈ 6.4 x 10^6 m), vesc = 11.2 km/s.
      """.trimIndent()
    ),

    StudyMaterial(
      id = "eng_1",
      subject = MDCATSubject.ENGLISH,
      title = "Subject-Verb Agreement & High-Yield Concord",
      chapter = "Grammar & Structure",
      readTimeMin = 8,
      highYieldPriority = "HIGH",
      keyConcepts = listOf(
        "Singular indefinite pronouns (each, either, neither, everyone, someone) take singular verbs.",
        "With correlative conjunctions 'Either...or' and 'Neither...nor', verb agrees with the closer subject.",
        "Phrases such as 'as well as', 'along with', 'in addition to' do not change the number of the main subject.",
        "'A number of' takes a PLURAL verb; 'The number of' takes a SINGULAR verb.",
        "Collective nouns (committee, jury, team) take singular verb when acting as a unit, plural when divided."
      ),
      mnemonics = listOf(
        "A number vs The number: 'A number = Abundant (plural); The number = Total (singular).'"
      ),
      formulas = listOf(
        "Subject + [as well as / together with + Noun] + Verb (agrees with first Subject)",
        "Neither A nor B + Verb (agrees with B)"
      ),
      contentMarkdown = """
# Concord: High-Yield MDCAT Rules

Subject-Verb Concord accounts for nearly 40% of MDCAT English error-detection questions.

## Rule 1: Correlative Conjunctions
When subjects are connected by *either...or*, *neither...nor*, or *not only...but also*, the verb agrees in number and person with the closest subject.
- *Example*: Neither the doctor nor the nurses **were** aware of the anomaly.
- *Example*: Neither the nurses nor the doctor **was** aware of the anomaly.

## Rule 2: Parenthetical Interventions
Phrases like *accompanied by*, *along with*, *as well as*, and *including* are parenthetical.
- *Example*: The surgeon, along with five junior residents, **is** performing the bypass.
      """.trimIndent()
    ),

    StudyMaterial(
      id = "logic_1",
      subject = MDCATSubject.LOGICAL_REASONING,
      title = "Critical Syllogisms & Deductive Logic",
      chapter = "Analytical Reasoning",
      readTimeMin = 7,
      highYieldPriority = "HIGH",
      keyConcepts = listOf(
        "Universal Affirmative: 'All A are B' does NOT automatically mean 'All B are A'.",
        "Converse fallacy: If P implies Q, Q does NOT necessarily imply P.",
        "Contrapositive equivalence: 'If P then Q' is logically equivalent to 'If not Q then not P'.",
        "Venn diagrams eliminate ambiguity in multi-statement syllogisms.",
        "Never assume real-world facts that contradict the given premise."
      ),
      mnemonics = listOf(
        "Contrapositive Rule: 'Flip both terms, reverse both signs!'"
      ),
      formulas = listOf(
        "Premise 1: All A are B",
        "Premise 2: Some B are C",
        "Valid deduction: Some C may be A, but cannot conclude definitively without overlap."
      ),
      contentMarkdown = """
# Syllogisms & Deductive Reasoning

In MDCAT Logical Reasoning, accept the premises as 100% true, even if they contradict common real-world knowledge.

## Venn Diagram Method
Draw overlapping circles for each category. A conclusion is valid ONLY if it holds true across ALL possible Venn configurations.
      """.trimIndent()
    )
  )

  val quizQuestions: List<QuizQuestion> = listOf(
    QuizQuestion(
      id = "q1",
      subject = MDCATSubject.BIOLOGY,
      topic = "Bioenergetics",
      questionText = "Which complex of the mitochondrial electron transport chain does NOT pump protons across the inner mitochondrial membrane into the intermembrane space?",
      options = listOf(
        "Complex I (NADH-Q oxidoreductase)",
        "Complex II (Succinate-Q reductase)",
        "Complex III (Q-cytochrome c oxidoreductase)",
        "Complex IV (Cytochrome c oxidase)"
      ),
      correctOptionIndex = 1,
      explanation = "Complex II (Succinate Dehydrogenase) contains FAD and transfers electrons directly from succinate to ubiquinone (Q) without translocating any protons across the inner membrane.",
      highYieldTip = "Complexes I, III, and IV pump 4, 4, and 2 protons per electron pair respectively."
    ),

    QuizQuestion(
      id = "q2",
      subject = MDCATSubject.BIOLOGY,
      topic = "Enzymes",
      questionText = "In competitive enzyme inhibition, how are the kinetic parameters Km and Vmax affected upon addition of the competitive inhibitor?",
      options = listOf(
        "Km increases; Vmax decreases",
        "Km remains unchanged; Vmax decreases",
        "Km increases; Vmax remains unchanged",
        "Both Km and Vmax decrease"
      ),
      correctOptionIndex = 2,
      explanation = "In competitive inhibition, the inhibitor binds the active site reversibly. Increasing substrate concentration overcomes inhibition, meaning Vmax is still reachable, but a higher substrate concentration is needed to reach 1/2 Vmax (Km increases).",
      highYieldTip = "Lineweaver-Burk plot shows competitive lines intersecting at the y-axis (1/Vmax)."
    ),

    QuizQuestion(
      id = "q3",
      subject = MDCATSubject.BIOLOGY,
      topic = "Genetics & DNA",
      questionText = "During eukaryotic DNA replication, which enzyme is responsible for removing RNA primers and replacing them with deoxyribonucleotides?",
      options = listOf(
        "DNA Polymerase III",
        "DNA Ligase",
        "DNA Polymerase I",
        "Helicase"
      ),
      correctOptionIndex = 2,
      explanation = "DNA Polymerase I possesses unique 5' to 3' exonuclease activity that excises RNA primers and synthesizes complementary DNA in their place.",
      highYieldTip = "DNA Ligase forms phosphodiester bonds to seal nicks between Okazaki fragments."
    ),

    QuizQuestion(
      id = "q4",
      subject = MDCATSubject.CHEMISTRY,
      topic = "Chemical Equilibrium",
      questionText = "For the exothermic reaction: 2SO2(g) + O2(g) ⇌ 2SO3(g) (ΔH = -198 kJ/mol), which change will increase both the equilibrium yield of SO3 and the value of Kc?",
      options = listOf(
        "Increasing the pressure",
        "Decreasing the temperature",
        "Adding a platinum catalyst",
        "Increasing the concentration of SO2"
      ),
      correctOptionIndex = 1,
      explanation = "Kc depends ONLY on temperature. For an exothermic reaction (ΔH < 0), lowering temperature shifts the equilibrium to the right, increasing both product yield and the numerical value of Kc.",
      highYieldTip = "Pressure increases yield of SO3 because moles decrease (3 to 2), but pressure CANNOT change Kc."
    ),

    QuizQuestion(
      id = "q5",
      subject = MDCATSubject.CHEMISTRY,
      topic = "Carbonyl Compounds",
      questionText = "Which of the following organic compounds will produce a bright yellow precipitate of iodoform (CHI3) when treated with iodine in aqueous sodium hydroxide?",
      options = listOf(
        "Methanol",
        "Propan-1-ol",
        "Propan-2-one (Acetone)",
        "Benzophenone"
      ),
      correctOptionIndex = 2,
      explanation = "The haloform/iodoform reaction requires compounds containing either the methyl carbonyl group (CH3-C=O) or methyl carbinol group (CH3-CH(OH)-). Acetone possesses two methyl carbonyl groups.",
      highYieldTip = "Ethanol is the ONLY primary alcohol that gives a positive iodoform test!"
    ),

    QuizQuestion(
      id = "q6",
      subject = MDCATSubject.PHYSICS,
      topic = "Mechanics",
      questionText = "A projectile is launched from ground level with speed v at an angle θ to the horizontal. At the highest point of its trajectory, what is its acceleration?",
      options = listOf(
        "Zero",
        "v² * cos²(θ) / R",
        "g, directed vertically downwards",
        "g * cos(θ)"
      ),
      correctOptionIndex = 2,
      explanation = "Throughout projectile motion (neglecting air resistance), gravity is the sole force acting, so acceleration is constant and equals g (9.8 m/s²) directed vertically downward at every point, including the peak.",
      highYieldTip = "At maximum height, vertical velocity is zero, but horizontal velocity is v*cos(θ) and acceleration is g downward."
    ),

    QuizQuestion(
      id = "q7",
      subject = MDCATSubject.PHYSICS,
      topic = "Work & Energy",
      questionText = "If the linear momentum of an electron is doubled, its kinetic energy increases by what factor?",
      options = listOf(
        "2 times",
        "4 times",
        "√2 times",
        "8 times"
      ),
      correctOptionIndex = 1,
      explanation = "Kinetic energy is related to momentum by K = p² / (2m). If momentum p is doubled to 2p, kinetic energy becomes (2p)² / (2m) = 4 * (p² / 2m), increasing 4-fold.",
      highYieldTip = "Percentage increase: A 100% increase in momentum leads to a 300% increase in kinetic energy."
    ),

    QuizQuestion(
      id = "q8",
      subject = MDCATSubject.ENGLISH,
      topic = "Concord",
      questionText = "Choose the grammatically correct sentence from the following options:",
      options = listOf(
        "The professor, along with his research assistants, were attending the symposium.",
        "The professor, along with his research assistants, was attending the symposium.",
        "The professor along with his research assistants have attended the symposium.",
        "The professor, along with his research assistants, are attending the symposium."
      ),
      correctOptionIndex = 1,
      explanation = "Parenthetical phrases introduced by 'along with', 'as well as', or 'accompanied by' do not affect the grammatical number of the subject. The singular subject 'The professor' requires the singular verb 'was attending'.",
      highYieldTip = "Ignore words between commas setting off parenthetical phrases when matching verbs!"
    ),

    QuizQuestion(
      id = "q9",
      subject = MDCATSubject.LOGICAL_REASONING,
      topic = "Deductive Logic",
      questionText = "Premise 1: All cardiologists are medical doctors.\nPremise 2: Some medical doctors are marathon runners.\nWhich conclusion logically follows with absolute certainty?",
      options = listOf(
        "All cardiologists are marathon runners.",
        "Some cardiologists are marathon runners.",
        "Some marathon runners are medical doctors.",
        "No cardiologist is a marathon runner."
      ),
      correctOptionIndex = 2,
      explanation = "From Premise 2: 'Some medical doctors are marathon runners', the converse 'Some marathon runners are medical doctors' is an immediate and certain logical deduction.",
      highYieldTip = "'Some A are B' always guarantees 'Some B are A'."
    )
  )

  val videoLectures: List<VideoLecture> = listOf(
    VideoLecture(
      id = "vid_1",
      title = "Cellular Respiration & Krebs Cycle Masterclass",
      subject = MDCATSubject.BIOLOGY,
      educatorName = "Dr salar (Lead Medical Faculty)",
      durationMinutes = 42,
      topic = "Bioenergetics",
      summaryNotes = "Complete breakdown of glycolysis ATP stoichiometry, PDH complex regulation, Krebs cycle carbon bookkeeping, and Complex I-IV proton gradients.",
      keyTimestamps = listOf(
        "00:00" to "Introduction & High-Yield Blueprint",
        "08:15" to "Glycolysis Irreversible Steps (PFK-1)",
        "19:40" to "Krebs Cycle Carbon Balance & Mnemonics",
        "31:20" to "Chemiosmotic ATP Synthase Calculations"
      )
    ),
    VideoLecture(
      id = "vid_2",
      title = "Organic Carbonyl Mechanisms & Distinction Tests",
      subject = MDCATSubject.CHEMISTRY,
      educatorName = "Dr salar (Lead Medical Faculty)",
      durationMinutes = 36,
      topic = "Aldehydes & Ketones",
      summaryNotes = "Step-by-step nucleophilic addition mechanisms, hemiacetal formations, Tollens vs Fehling tests, and haloform reaction diagnostics.",
      keyTimestamps = listOf(
        "00:00" to "Carbonyl Reactivity & Polarization",
        "11:30" to "Aldehyde vs Ketone Distinction Tests",
        "22:15" to "Iodoform Reaction Step-by-Step",
        "32:00" to "Aldol Condensation & Cannizzaro Review"
      )
    ),
    VideoLecture(
      id = "vid_3",
      title = "Projectile Motion & Mechanics Shortcuts",
      subject = MDCATSubject.PHYSICS,
      educatorName = "Prof. Tariq & Dr salar",
      durationMinutes = 38,
      topic = "Mechanics & Projectiles",
      summaryNotes = "Eliminate calculation errors on maximum height, range formulas, complementary angle theorems, and momentum conservation in 2D collisions.",
      keyTimestamps = listOf(
        "00:00" to "Resolving Velocity Components",
        "09:45" to "Time of Flight & Maximum Height",
        "18:20" to "Complementary Launch Angles Theorem",
        "28:50" to "Solved Past MDCAT Past Paper MCQs"
      )
    ),
    VideoLecture(
      id = "vid_4",
      title = "MDCAT Vocabulary Roots & Context Clues",
      subject = MDCATSubject.ENGLISH,
      educatorName = "Dr salar",
      durationMinutes = 24,
      topic = "Vocabulary & Concord",
      summaryNotes = "Greek and Latin roots, prefixes and suffixes, context clues elimination strategy, and high-frequency MDCAT words.",
      keyTimestamps = listOf(
        "00:00" to "Root Words Decoded",
        "07:30" to "Top 50 Recurring MDCAT Synonyms",
        "16:45" to "Concord Pitfalls & Practice Drills"
      )
    )
  )

  val forumPosts: List<ForumPost> = listOf(
    ForumPost(
      id = "post_1",
      authorName = "Ayesha Malik",
      authorTag = "MDCAT Aspirant • Lahore",
      title = "Confusion on Complex II in Oxidative Phosphorylation - why no H+ pumping?",
      content = "Can someone clarify why Complex II doesn't pump protons? In past papers I got confused between Complex I and Complex II ATP yield.",
      subject = MDCATSubject.BIOLOGY,
      upvotes = 24,
      isUpvoted = true,
      isResolved = true,
      timestampMillis = System.currentTimeMillis() - (3 * 3600 * 1000),
      answers = listOf(
        ForumAnswer(
          id = "ans_1",
          authorName = "Dr salar",
          authorTag = "Lead Educator • Developer",
          content = "Great question Ayesha! Complex II (Succinate Dehydrogenase) spans the inner mitochondrial membrane but does not traverse all the way across to the intermembrane space. The redox potential difference between FADH2 and Ubiquinone is not large enough to generate sufficient free energy to pump protons against the electrochemical gradient. That is why 1 FADH2 yields only ~1.5 ATP while 1 NADH yields ~2.5 ATP via Complex I.",
          timestampMillis = System.currentTimeMillis() - (2 * 3600 * 1000),
          isVerifiedEducator = true,
          upvotes = 38
        )
      )
    ),
    ForumPost(
      id = "post_2",
      authorName = "Zubair Ahmed",
      authorTag = "MDCAT Aspirant • Karachi",
      title = "Shortcut for Le Chatelier pressure questions when inert gas is added?",
      content = "Does adding an inert gas at constant volume change the equilibrium yield? What about at constant pressure?",
      subject = MDCATSubject.CHEMISTRY,
      upvotes = 18,
      isUpvoted = false,
      isResolved = true,
      timestampMillis = System.currentTimeMillis() - (8 * 3600 * 1000),
      answers = listOf(
        ForumAnswer(
          id = "ans_2",
          authorName = "Hamza R.",
          authorTag = "Senior MDCAT Peer",
          content = "At CONSTANT VOLUME: Inert gas increases total pressure, but partial pressures of reactants/products remain unchanged, so NO shift! At CONSTANT PRESSURE: Adding gas increases volume, lowering partial pressures, shifting toward the side with MORE moles of gas!",
          timestampMillis = System.currentTimeMillis() - (5 * 3600 * 1000),
          isVerifiedEducator = false,
          upvotes = 15
        )
      )
    )
  )

  val studyGroups: List<StudyGroup> = listOf(
    StudyGroup(
      id = "grp_1",
      name = "King Edward & KEMU Aspirants 2026",
      targetBatch = "Target: 190+ Score",
      memberCount = 342,
      subjectFocus = MDCATSubject.BIOLOGY,
      description = "Daily 50-MCQ challenge group focusing on Bioenergetics, Human Physiology, and Genetics high-yield drills.",
      recentDiscussion = "Ayesha posted a mnemonic summary for Cranial Nerves.",
      sharedResourcesCount = 48
    ),
    StudyGroup(
      id = "grp_2",
      name = "Organic Chemistry Mastery Circle",
      targetBatch = "Target: 54/54 in Chemistry",
      memberCount = 215,
      subjectFocus = MDCATSubject.CHEMISTRY,
      description = "Doubt clearing for Aldehydes, Ketones, Benzene substitution, and Reaction Kinetics.",
      recentDiscussion = "Zain shared handwritten notes on Carbonyl condensation reactions.",
      sharedResourcesCount = 32
    ),
    StudyGroup(
      id = "grp_3",
      name = "Physics Numerical Crunchers",
      targetBatch = "All Pakistan MDCAT",
      memberCount = 189,
      subjectFocus = MDCATSubject.PHYSICS,
      description = "Rapid formula application, speed drills, and Doppler Effect numerical solving sessions.",
      recentDiscussion = "Bilal solved the 2024 projectile motion question using energy shortcut.",
      sharedResourcesCount = 27
    )
  )

  val initialEncryptedNotes: List<EncryptedNote> = listOf(
    EncryptedNote(
      id = "note_1",
      title = "High-Yield Hormone Secretion Flash-Sheet",
      subject = MDCATSubject.BIOLOGY,
      rawContent = "• Anterior Pituitary: TSH, ACTH, FSH, LH, GH, Prolactin.\n• Posterior Pituitary (stored only): ADH (Vasopressin) & Oxytocin produced by Hypothalamus.\n• Adrenal Cortex: Aldosterone (zona glomerulosa), Cortisol (zona fasciculata), Androgens (zona reticularis).\n• Adrenal Medulla: Epinephrine & Norepinephrine (Catecholamines).\n• Calcitonin (Thyroid C-cells) LOWERS blood calcium; PTH (Parathyroid) RAISES blood calcium.",
      isEncrypted = true,
      encryptionAlgorithm = "AES-256-GCM (End-to-End)",
      isPinned = true
    ),
    EncryptedNote(
      id = "note_2",
      title = "Physics Electrostatics Formula Summary",
      subject = MDCATSubject.PHYSICS,
      rawContent = "• Coulomb Force: F = k*q1*q2 / r² where k = 1/(4πε0) ≈ 9 x 10^9 N·m²/C².\n• Electric Field: E = F/q = k*Q / r².\n• Electric Potential: V = k*Q / r (scalar!).\n• Capacitance: C = εr * ε0 * A / d.\n• Energy stored in capacitor: U = (1/2)CV² = (1/2)Q*V = Q²/(2C).",
      isEncrypted = true,
      encryptionAlgorithm = "AES-256-GCM (End-to-End)",
      isPinned = false
    )
  )

  val initialCalendarEvents: List<CalendarEvent> = listOf(
    CalendarEvent(
      id = "event_1",
      title = "Full-Length MDCAT Grand Mock #1",
      dateMillis = System.currentTimeMillis() + (3L * 24 * 3600 * 1000),
      eventType = CalendarEventType.MOCK_TEST,
      notes = "Simulate 3.5 hours uninterrupted test environment under timed conditions.",
      isCompleted = false
    ),
    CalendarEvent(
      id = "event_2",
      title = "Complete Biology Revision: Cell & Genetics",
      dateMillis = System.currentTimeMillis() + (5L * 24 * 3600 * 1000),
      eventType = CalendarEventType.REVISION,
      notes = "Review Dr salar's notes and solve 80 MCQs.",
      isCompleted = false
    ),
    CalendarEvent(
      id = "event_3",
      title = "Official MDCAT Exam Day",
      dateMillis = System.currentTimeMillis() + (72L * 24 * 3600 * 1000),
      eventType = CalendarEventType.EXAM,
      notes = "Target score: 185+/200 for admission to Top Medical Colleges.",
      isCompleted = false
    )
  )

  val initialBadges: List<BadgeItem> = listOf(
    BadgeItem(
      id = "badge_streak",
      title = "7-Day Streak Master",
      description = "Maintained a continuous 7-day study habit without missing a session.",
      iconName = "LocalFireDepartment",
      isUnlocked = true,
      progress = 1.0f
    ),
    BadgeItem(
      id = "badge_bio_whiz",
      title = "Biology Whiz",
      description = "Scored over 90% in Cell Biology and Bioenergetics practice quizzes.",
      iconName = "Psychology",
      isUnlocked = true,
      progress = 1.0f
    ),
    BadgeItem(
      id = "badge_chem_pro",
      title = "Carbonyl Champion",
      description = "Mastered organic reaction mechanisms and chemical equilibrium.",
      iconName = "Science",
      isUnlocked = false,
      progress = 0.65f
    ),
    BadgeItem(
      id = "badge_night_owl",
      title = "Night Owl Scholar",
      description = "Logged 3 late-night study sessions using Late-Night Eye-Comfort Mode.",
      iconName = "Bedtime",
      isUnlocked = true,
      progress = 1.0f
    ),
    BadgeItem(
      id = "badge_ranker",
      title = "MDCAT Merit Ranker",
      description = "Complete 5 full-length mock exams with overall accuracy above 85%.",
      iconName = "WorkspacePremium",
      isUnlocked = false,
      progress = 0.40f
    )
  )

  val initialPdfResources: List<com.example.data.model.PdfResource> = listOf(
    com.example.data.model.PdfResource(
      id = "pdf_1",
      title = "UHS & PMC Past Papers Solved (2018-2025)",
      subject = com.example.data.model.MDCATSubject.BIOLOGY,
      chapter = "Full MDCAT Syllabus",
      fileSizeMb = 14.2f,
      pdfUrlOrPath = "https://mdcatmaster.edu.pk/resources/uhs_past_papers_solved.pdf",
      uploadedBy = "Dr. Salar",
      description = "Comprehensive authentic past questions with high-yield rationale and tricky options explained."
    ),
    com.example.data.model.PdfResource(
      id = "pdf_2",
      title = "Dr. Salar's Organic Chemistry Reaction Maps",
      subject = com.example.data.model.MDCATSubject.CHEMISTRY,
      chapter = "Organic Chemistry",
      fileSizeMb = 8.5f,
      pdfUrlOrPath = "https://mdcatmaster.edu.pk/resources/dr_salar_organic_maps.pdf",
      uploadedBy = "Dr. Salar",
      description = "Visual flowchart maps of all carbonyl, alkyl halide, benzene, and carboxylic reactions for fast recall.",
      academicClass = AcademicClass.CLASS_12
    ),
    com.example.data.model.PdfResource(
      id = "pdf_3",
      title = "MDCAT Physics Formula Handbook & Derivations",
      subject = com.example.data.model.MDCATSubject.PHYSICS,
      chapter = "Mechanics & Modern Physics",
      fileSizeMb = 6.1f,
      pdfUrlOrPath = "https://mdcatmaster.edu.pk/resources/physics_formula_handbook.pdf",
      uploadedBy = "Dr. Salar",
      description = "All core formulas, unit dimensions, proportionality shortcuts, and projectile angle tables.",
      academicClass = AcademicClass.CLASS_11
    )
  )

  val initialDraftNotes: List<StudyNoteDraft> = listOf(
    StudyNoteDraft(
      id = "draft_1",
      title = "Nerve Impulse & Synaptic Transmission Dynamics",
      subject = MDCATSubject.BIOLOGY,
      academicClass = AcademicClass.CLASS_12,
      chapter = "Coordination & Control",
      readTimeMin = 12,
      keyConceptsRaw = "Resting membrane potential is -70mV maintained by Na+/K+ ATPase pump (3 Na+ out, 2 K+ in)\nDepolarization triggered at threshold -55mV via voltage-gated Na+ channels opening\nRepolarization occurs as voltage-gated K+ channels open and Na+ channels inactivate\nSaltatory conduction in myelinated axons speeds velocity up to 120 m/s",
      mnemonicsRaw = "Na+/K+ Pump: '3-2-1 NOK' (3 Na+ Out, 2 K+ In, 1 ATP spent)\nDepolarization vs Repolarization: 'Na+ Rushes In to Excite; K+ Walks Out to Set it Right'",
      contentMarkdown = "# Nervous Coordination & Synaptic Transmission\n\n*Draft prepared by Dr. Salar for 12th Class Pre-Medical syllabus.*\n\n## 1. Action Potential Phases\n- Resting: -70 mV\n- Threshold: -55 mV\n- Peak Depolarization: +30 to +40 mV\n- Refractory period prevents reverse transmission.",
      linkedPdfUrl = "https://mdcatmaster.edu.pk/drafts/action_potential_preview.pdf",
      lastSavedMillis = System.currentTimeMillis() - (2 * 3600 * 1000L)
    ),
    StudyNoteDraft(
      id = "draft_2",
      title = "Stoichiometry & Limiting Reactant Calculations",
      subject = MDCATSubject.CHEMISTRY,
      academicClass = AcademicClass.CLASS_11,
      chapter = "Stoichiometry",
      readTimeMin = 8,
      keyConceptsRaw = "Limiting reactant gives minimum amount of product\nTheoretical yield is calculated strictly from limiting reactant stoichiometry\nPercentage yield = (Actual yield / Theoretical yield) * 100",
      mnemonicsRaw = "Limiting Reactant: 'Least Moles of Product Identifies the Boss'",
      contentMarkdown = "# Fundamental Stoichiometry Shortcuts\n\n*Draft compiled by Dr. Salar for 11th Class students.*\n\nMaster the ratio comparison method rather than full unitary conversions to save crucial MDCAT minutes.",
      linkedPdfUrl = "",
      lastSavedMillis = System.currentTimeMillis() - (5 * 3600 * 1000L)
    )
  )

  val initialCourseSubscriptions: List<com.example.data.model.CourseSubscription> = listOf(
    com.example.data.model.CourseSubscription(
      courseId = "course_mdcat_full",
      title = "MDCAT Complete Masterclass 2026",
      subjectFocus = "Complete Combined Pre-Medical Syllabus",
      targetClass = null,
      instructor = "Dr. Salar",
      pricePkr = 6500,
      originalPricePkr = 12000,
      durationWeeks = 16,
      description = "The ultimate comprehensive preparation bundle curated by Dr. Salar. Covers all 11th & 12th topics in Biology, Chemistry, Physics, English & Logic with live sessions, 5,000+ MCQs, and full PDF handbooks.",
      features = listOf(
        "Full 11th & 12th class video lectures & notes",
        "Weekly Live interactive webinars with Dr. Salar",
        "5,000+ Practice MCQs with detailed explanations",
        "10 Full-Length PMC-Pattern Mock Examinations",
        "Unlimited PDF handbook downloads & formulas"
      ),
      isSubscribed = true,
      badge = "FLAGSHIP",
      totalSubscribers = 1850
    ),
    com.example.data.model.CourseSubscription(
      courseId = "course_bio_11",
      title = "11th Class (FSc-I) Pre-Medical Foundation",
      subjectFocus = "Biology & Chemistry Concept Mastery",
      targetClass = AcademicClass.CLASS_11,
      instructor = "Dr. Salar",
      pricePkr = 3200,
      originalPricePkr = 6000,
      durationWeeks = 10,
      description = "Master cell biology, enzymes, bioenergetics, stoichiometry, and fundamental physical laws with Dr. Salar's structured First Year curriculum.",
      features = listOf(
        "Complete 11th class syllabus coverage",
        "High-yield mnemonics and memory retention tricks",
        "1,500+ chapter-wise practice MCQs",
        "Monthly live doubt resolution sessions"
      ),
      isSubscribed = true,
      badge = "11th CLASS",
      totalSubscribers = 940
    ),
    com.example.data.model.CourseSubscription(
      courseId = "course_physics_12",
      title = "12th Class (FSc-II) Organic Chemistry & Genetics Booster",
      subjectFocus = "Coordination, Genetics, Organic Chemistry, Electromagnetism",
      targetClass = AcademicClass.CLASS_12,
      instructor = "Dr. Salar",
      pricePkr = 3500,
      originalPricePkr = 6500,
      durationWeeks = 10,
      description = "Dedicated booster course for Second Year students tackling high-weightage topics: reaction mechanisms, DNA replication, nervous coordination, and electromagnetism.",
      features = listOf(
        "Deep dive into organic reaction pathways",
        "Genetics pedigree analysis and probability problem solving",
        "2,000+ challenging Second Year MCQs",
        "Exclusive solved past paper handbook (PDF)"
      ),
      isSubscribed = false,
      badge = "12th CLASS",
      totalSubscribers = 1120
    ),
    com.example.data.model.CourseSubscription(
      courseId = "course_crash_test",
      title = "Dr. Salar's 5,000+ High-Yield MCQ & Test Series Crash Course",
      subjectFocus = "Targeted Question Solving & Time Strategy",
      targetClass = null,
      instructor = "Dr. Salar",
      pricePkr = 2800,
      originalPricePkr = 5000,
      durationWeeks = 6,
      description = "Intensive 6-week problem solving bootcamp designed to boost your score above 180+. Features timed mock drills, trap avoidance tips, and live test reviews.",
      features = listOf(
        "5,000+ authentic MDCAT past & modeled questions",
        "Trap detection strategies to eliminate distractors",
        "Live question walkthroughs with Dr. Salar",
        "Speed & accuracy performance analytics"
      ),
      isSubscribed = false,
      badge = "CRASH COURSE",
      totalSubscribers = 1430
    )
  )

  val initialLiveSessions: List<com.example.data.model.LiveSession> = listOf(
    com.example.data.model.LiveSession(
      id = "live_1",
      title = "Dr. Salar's Live MDCAT Masterclass: Bioenergetics & Respiration Shortcuts",
      instructorName = "Dr. Salar",
      subject = MDCATSubject.BIOLOGY,
      academicClass = AcademicClass.CLASS_11,
      scheduledTimeMillis = System.currentTimeMillis() + (45 * 60 * 1000L), // 45 mins from now
      durationMinutes = 75,
      meetingUrl = "https://meet.google.com/mdcat-salar-live",
      status = com.example.data.model.LiveSessionStatus.LIVE_NOW,
      agenda = "1. Glycolysis regulatory enzymes & substrate-level vs oxidative phosphorylation\n2. Krebs cycle bookkeeping and high-frequency exam traps\n3. Solving 25 past PMC bioenergetics MCQs in 15 minutes\n4. Open student Q&A with Dr. Salar",
      attendeesCount = 384,
      recordingUrl = null
    ),
    com.example.data.model.LiveSession(
      id = "live_2",
      title = "Organic Reaction Mechanisms: Electrophilic Substitution & SN1/SN2 Mastery",
      instructorName = "Dr. Salar",
      subject = MDCATSubject.CHEMISTRY,
      academicClass = AcademicClass.CLASS_12,
      scheduledTimeMillis = System.currentTimeMillis() + (24 * 3600 * 1000L), // Tomorrow
      durationMinutes = 60,
      meetingUrl = "https://meet.google.com/mdcat-chem-live",
      status = com.example.data.model.LiveSessionStatus.UPCOMING,
      agenda = "1. Carbocation stability and Markovnikov's rule in depth\n2. Comparing SN1 vs SN2 solvent and stereochemistry effects\n3. Live problem solving for benzene nitration and acylation",
      attendeesCount = 215,
      recordingUrl = null
    ),
    com.example.data.model.LiveSession(
      id = "live_3",
      title = "Physics Electromagnetism & Right-Hand Rules Speed Workshop",
      instructorName = "Dr. Salar",
      subject = MDCATSubject.PHYSICS,
      academicClass = AcademicClass.CLASS_12,
      scheduledTimeMillis = System.currentTimeMillis() - (48 * 3600 * 1000L), // Past
      durationMinutes = 80,
      meetingUrl = "https://meet.google.com/mdcat-physics-recorded",
      status = com.example.data.model.LiveSessionStatus.RECORDED,
      agenda = "Recorded session covering Biot-Savart law, Ampere's circuital law, Faraday's electromagnetic induction, and Lenz's law numericals.",
      attendeesCount = 520,
      recordingUrl = "https://mdcatmaster.edu.pk/recordings/electromagnetism_session.mp4"
    )
  )
}
